// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"email-send-manager/internal/app/api"
	"email-send-manager/internal/app/dao/customer"
	"email-send-manager/internal/app/dao/record"
	"email-send-manager/internal/app/dao/setting"
	"email-send-manager/internal/app/dao/template"
	"email-send-manager/internal/app/dao/util"
	"email-send-manager/internal/app/router"
	"email-send-manager/internal/app/service"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	customerRepo := &customer.CustomerRepo{
		DB: db,
	}
	customerSrv := &service.CustomerSrv{
		TransRepo:    trans,
		CustomerRepo: customerRepo,
	}
	customerAPI := &api.CustomerAPI{
		CustomerSrv: customerSrv,
	}
	templateRepo := &template.TemplateRepo{
		DB: db,
	}
	templateSrv := &service.TemplateSrv{
		TransRepo:    trans,
		TemplateRepo: templateRepo,
	}
	templateAPI := &api.TemplateAPI{
		TemplateSrv: templateSrv,
	}
	recordRepo := &record.RecordRepo{
		DB: db,
	}
	recordSrv := &service.RecordSrv{
		TransRepo:  trans,
		RecordRepo: recordRepo,
	}
	recordAPI := &api.RecordAPI{
		RecordSrv: recordSrv,
	}
	settingRepo := &setting.SettingRepo{
		DB: db,
	}
	sendBatchSrv := &service.SendBatchSrv{
		TransRepo:    trans,
		CustomerRepo: customerRepo,
		TemplateRepo: templateRepo,
		SettingRepo:  settingRepo,
		RecordRepo:   recordRepo,
	}
	sendBatchAPI := &api.SendBatchAPI{
		SendBatchSrv: sendBatchSrv,
	}
	settingSrv := &service.SettingSrv{
		TransRepo:   trans,
		SettingRepo: settingRepo,
	}
	settingAPI := &api.SettingAPI{
		SettingSrv: settingSrv,
	}
	routerRouter := &router.Router{
		CustomerAPI:  customerAPI,
		TemplateAPI:  templateAPI,
		RecordAPI:    recordAPI,
		SendBatchAPI: sendBatchAPI,
		SettingAPI:   settingAPI,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
		cleanup()
	}, nil
}
